export const COMMAND_IDS = {
  explainFile: "howItWorks.explainFile",
  explainFileAuto: "howItWorks.explainFile.auto",
  explainFileEn: "howItWorks.explainFile.en",
  explainFileEs: "howItWorks.explainFile.es",
  explainFileFr: "howItWorks.explainFile.fr",
  explainFileDe: "howItWorks.explainFile.de",
  explainFileIt: "howItWorks.explainFile.it",
  explainFilePt: "howItWorks.explainFile.pt",
  explainFileZh: "howItWorks.explainFile.zh",
  explainFileJa: "howItWorks.explainFile.ja",
  explainFileKo: "howItWorks.explainFile.ko",
  readExplanationAuto: "howItWorks.readExplanation.auto",
  readExplanationEn: "howItWorks.readExplanation.en",
  readExplanationEs: "howItWorks.readExplanation.es",
  readExplanationFr: "howItWorks.readExplanation.fr",
  readExplanationDe: "howItWorks.readExplanation.de",
  readExplanationIt: "howItWorks.readExplanation.it",
  readExplanationPt: "howItWorks.readExplanation.pt",
  readExplanationZh: "howItWorks.readExplanation.zh",
  readExplanationJa: "howItWorks.readExplanation.ja",
  readExplanationKo: "howItWorks.readExplanation.ko",
  setupExtension: "howItWorks.setupExtension",
  setApiKey: "howItWorks.setApiKey",
  setLanguage: "howItWorks.setLanguage",
  setLanguageAuto: "howItWorks.setLanguage.auto",
  setLanguageEn: "howItWorks.setLanguage.en",
  setLanguageEs: "howItWorks.setLanguage.es",
  setLanguageFr: "howItWorks.setLanguage.fr",
  setLanguageDe: "howItWorks.setLanguage.de",
  setLanguageIt: "howItWorks.setLanguage.it",
  setLanguagePt: "howItWorks.setLanguage.pt",
  setLanguageZh: "howItWorks.setLanguage.zh",
  setLanguageJa: "howItWorks.setLanguage.ja",
  setLanguageKo: "howItWorks.setLanguage.ko",
  regenerateExplanation: "howItWorks.regenerateExplanation",
  regenerateExplanationAuto: "howItWorks.regenerateExplanation.auto",
  regenerateExplanationEn: "howItWorks.regenerateExplanation.en",
  regenerateExplanationEs: "howItWorks.regenerateExplanation.es",
  regenerateExplanationFr: "howItWorks.regenerateExplanation.fr",
  regenerateExplanationDe: "howItWorks.regenerateExplanation.de",
  regenerateExplanationIt: "howItWorks.regenerateExplanation.it",
  regenerateExplanationPt: "howItWorks.regenerateExplanation.pt",
  regenerateExplanationZh: "howItWorks.regenerateExplanation.zh",
  regenerateExplanationJa: "howItWorks.regenerateExplanation.ja",
  regenerateExplanationKo: "howItWorks.regenerateExplanation.ko",
  regenerateAndReadExplanationAuto: "howItWorks.regenerateAndReadExplanation.auto",
  regenerateAndReadExplanationEn: "howItWorks.regenerateAndReadExplanation.en",
  regenerateAndReadExplanationEs: "howItWorks.regenerateAndReadExplanation.es",
  regenerateAndReadExplanationFr: "howItWorks.regenerateAndReadExplanation.fr",
  regenerateAndReadExplanationDe: "howItWorks.regenerateAndReadExplanation.de",
  regenerateAndReadExplanationIt: "howItWorks.regenerateAndReadExplanation.it",
  regenerateAndReadExplanationPt: "howItWorks.regenerateAndReadExplanation.pt",
  regenerateAndReadExplanationZh: "howItWorks.regenerateAndReadExplanation.zh",
  regenerateAndReadExplanationJa: "howItWorks.regenerateAndReadExplanation.ja",
  regenerateAndReadExplanationKo: "howItWorks.regenerateAndReadExplanation.ko",
} as const;

export const GENERATE_AND_READ_COMMAND_VARIANTS = [
  COMMAND_IDS.explainFile,
  COMMAND_IDS.explainFileAuto,
  COMMAND_IDS.explainFileEn,
  COMMAND_IDS.explainFileEs,
  COMMAND_IDS.explainFileFr,
  COMMAND_IDS.explainFileDe,
  COMMAND_IDS.explainFileIt,
  COMMAND_IDS.explainFilePt,
  COMMAND_IDS.explainFileZh,
  COMMAND_IDS.explainFileJa,
  COMMAND_IDS.explainFileKo,
] as const;

export const READ_EXPLANATION_COMMAND_VARIANTS = [
  COMMAND_IDS.readExplanationAuto,
  COMMAND_IDS.readExplanationEn,
  COMMAND_IDS.readExplanationEs,
  COMMAND_IDS.readExplanationFr,
  COMMAND_IDS.readExplanationDe,
  COMMAND_IDS.readExplanationIt,
  COMMAND_IDS.readExplanationPt,
  COMMAND_IDS.readExplanationZh,
  COMMAND_IDS.readExplanationJa,
  COMMAND_IDS.readExplanationKo,
] as const;

export const SET_LANGUAGE_COMMAND_VARIANTS = [
  COMMAND_IDS.setLanguage,
  COMMAND_IDS.setLanguageAuto,
  COMMAND_IDS.setLanguageEn,
  COMMAND_IDS.setLanguageEs,
  COMMAND_IDS.setLanguageFr,
  COMMAND_IDS.setLanguageDe,
  COMMAND_IDS.setLanguageIt,
  COMMAND_IDS.setLanguagePt,
  COMMAND_IDS.setLanguageZh,
  COMMAND_IDS.setLanguageJa,
  COMMAND_IDS.setLanguageKo,
] as const;

export const REGENERATE_EXPLANATION_COMMAND_VARIANTS = [
  COMMAND_IDS.regenerateExplanation,
  COMMAND_IDS.regenerateExplanationAuto,
  COMMAND_IDS.regenerateExplanationEn,
  COMMAND_IDS.regenerateExplanationEs,
  COMMAND_IDS.regenerateExplanationFr,
  COMMAND_IDS.regenerateExplanationDe,
  COMMAND_IDS.regenerateExplanationIt,
  COMMAND_IDS.regenerateExplanationPt,
  COMMAND_IDS.regenerateExplanationZh,
  COMMAND_IDS.regenerateExplanationJa,
  COMMAND_IDS.regenerateExplanationKo,
] as const;

export const REGENERATE_AND_READ_EXPLANATION_COMMAND_VARIANTS = [
  COMMAND_IDS.regenerateAndReadExplanationAuto,
  COMMAND_IDS.regenerateAndReadExplanationEn,
  COMMAND_IDS.regenerateAndReadExplanationEs,
  COMMAND_IDS.regenerateAndReadExplanationFr,
  COMMAND_IDS.regenerateAndReadExplanationDe,
  COMMAND_IDS.regenerateAndReadExplanationIt,
  COMMAND_IDS.regenerateAndReadExplanationPt,
  COMMAND_IDS.regenerateAndReadExplanationZh,
  COMMAND_IDS.regenerateAndReadExplanationJa,
  COMMAND_IDS.regenerateAndReadExplanationKo,
] as const;
